# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ShiftJIS-X0213-MapUTF
version:      0.31
version_from: MapUTF.pm
installdirs:  site
requires:
    Carp:                          0
    DynaLoader:                    0
    Exporter:                      0
    strict:                        0
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
